In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

## Data Loading

In [ ]:
df = pd.read_csv('heart_disease.csv')
df

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4233,1,50,1.0,1,1.0,0.0,0,1,0,313.0,179.0,92.0,25.97,66.0,86.0,1
4234,1,51,3.0,1,43.0,0.0,0,0,0,207.0,126.5,80.0,19.71,65.0,68.0,0
4235,0,48,2.0,1,20.0,NaN,0,0,0,248.0,131.0,72.0,22.00,84.0,86.0,0
4236,0,44,1.0,1,15.0,0.0,0,0,0,210.0,126.5,87.0,19.16,86.0,NaN,0
4237,0,52,2.0,0,0.0,0.0,0,0,0,269.0,133.5,83.0,21.47,80.0,107.0,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4238 entries, 0 to 4237
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   male             4238 non-null   int64
 1   age              4238 non-null   int64
 2   education        4133 non-null   float64
 3   currentSmoker    4238 non-null   int64
 4   cigsPerDay       4209 non-null   float64
 5   BPMeds           4185 non-null   float64
 6   prevalentStroke  4238 non-null   int64
 7   prevalentHyp     4238 non-null   int64
 8   diabetes         4238 non-null   int64
 9   totChol          4188 non-null   float64
 10  sysBP            4238 non-null   float64
 11  diaBP            4238 non-null   float64
 12  BMI              4219 non-null   float64
 13  heartRate        4237 non-null   float64
 14  glucose          3850 non-null   float64
 15  TenYearCHD       4238 non-null   int64
dtypes: float64(9), int64(7)
memory usage: 529.9 KB

In [ ]:
df.isnull().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

## Data Cleaning

In [ ]:
df['education'].value_counts()

education
1.0    1720
2.0    1253
3.0     687
4.0     473
Name: count, dtype: int64

In [ ]:
df['education'] = df['education'].fillna(df['education'].mode()[0])

In [ ]:
df['education'].isnull().sum()

np.int64(0)

In [ ]:
df['cigsPerDay'].value_counts()

cigsPerDay
0.0     2144
20.0     734
30.0     217
15.0     210
10.0     143
9.0      130
5.0      121
3.0      100
40.0      80
1.0       67
43.0      56
25.0      55
35.0      22
6.0       18
2.0       18
7.0       12
60.0      11
8.0       11
4.0        9
18.0       8
17.0       7
50.0       6
23.0       6
11.0       5
12.0       3
45.0       3
13.0       3
16.0       3
14.0       2
19.0       2
38.0       1
29.0       1
70.0       1
Name: count, dtype: int64

In [ ]:
df['cigsPerDay'] = df['cigsPerDay'].fillna(df['cigsPerDay'].median())
df['cigsPerDay'].isnull().sum()

np.int64(0)

In [ ]:
df['totChol'] = df['totChol'].fillna(df['totChol'].median())
df['BMI'] = df['BMI'].fillna(df['BMI'].median())
df['heartRate'] = df['heartRate'].fillna(df['heartRate'].median())
df['glucose'] = df['glucose'].fillna(df['glucose'].median())
df.isnull().sum()

male                0
age                 0
education           0
currentSmoker       0
cigsPerDay          0
BPMeds             53
prevalentStroke     0
prevalentHyp        0
diabetes            0
totChol             0
sysBP               0
diaBP               0
BMI                 0
heartRate           0
glucose             0
TenYearCHD          0
dtype: int64

In [ ]:
df['BPMeds'].value_counts()

BPMeds
0.0    4061
1.0     124
Name: count, dtype: int64

In [ ]:
df['BPMeds'] = df['BPMeds'].fillna(0.0)

In [ ]:
df.isnull().sum()

male               0
age                0
education          0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [ ]:
df.head()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0

In [ ]:
df.to_csv('heart_disease_cleaned.csv',index=False)

## Train Test split

In [ ]:
X = df.drop('TenYearCHD', axis=1)
y = df['TenYearCHD']

In [ ]:
X

      male  age  education  currentSmoker  ...  diaBP    BMI  heartRate  glucose
0        1   39        4.0              0  ...   70.0  26.97       80.0     77.0
1        0   46        2.0              0  ...   81.0  28.73       95.0     76.0
2        1   48        1.0              1  ...   80.0  25.34       75.0     70.0
3        0   61        3.0              1  ...   95.0  28.58       65.0    103.0
4        0   46        3.0              1  ...   84.0  23.10       85.0     85.0
...    ...  ...        ...            ...  ...    ...    ...        ...      ...
4233     1   50        1.0              1  ...   92.0  25.97       66.0     86.0
4234     1   51        3.0              1  ...   80.0  19.71       65.0     68.0
4235     0   48        2.0              1  ...   72.0  22.00       84.0     86.0
4236     0   44        1.0              1  ...   87.0  19.16       86.0     78.0
4237     0   52        2.0              0  ...   83.0  21.47       80.0    107.0

[4238 rows x 15 columns]

In [ ]:
y

0       0
1       0
2       0
3       1
4       0
       ..
4233    1
4234    0
4235    0
4236    0
4237    0
Name: TenYearCHD, Length: 4238, dtype: int64

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.20,random_state=42)

In [ ]:
X_train.shape

(3390, 15)

In [ ]:
X_test.shape

(848, 15)

In [ ]:
df[df['TenYearCHD']==1]

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
6,0,63,1.0,0,0.0,0.0,0,0,0,205.0,138.0,71.0,33.11,60.0,85.0,1
15,0,38,2.0,1,20.0,0.0,0,1,0,221.0,140.0,90.0,21.35,95.0,70.0,1
17,0,46,2.0,1,20.0,0.0,0,0,0,291.0,112.0,78.0,23.38,80.0,89.0,1
25,1,47,4.0,1,20.0,0.0,0,0,0,294.0,102.0,68.0,24.18,62.0,66.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4221,1,50,1.0,0,0.0,0.0,0,0,0,260.0,119.0,74.0,21.85,80.0,72.0,1
4223,1,56,4.0,0,0.0,1.0,0,1,0,287.0,149.0,98.0,21.68,90.0,75.0,1
4226,1,58,1.0,0,0.0,0.0,0,0,0,233.0,125.5,84.0,26.05,67.0,76.0,1
4232,1,68,1.0,0,0.0,0.0,0,1,0,176.0,168.0,97.0,23.14,60.0,79.0,1
4233,1,50,1.0,1,1.0,0.0,0,1,0,313.0,179.0,92.0,25.97,66.0,86.0,1

## Scaling

In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## Model Training

In [ ]:
model = LogisticRegression()
model.fit(X_train,y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
Log_model = LogisticRegression()
Log_model.fit(X_train_scaled,y_train)

LogisticRegression()

In [ ]:
y_predict = Log_model.predict(X_test_scaled)

In [ ]:
y_predict_proba = Log_model.predict_proba(X_test_scaled)
y_predict_proba

array([[0.66794536, 0.33205464],
       [0.92163785, 0.07836215],
       [0.90563358, 0.09436642],
       ...,
       [0.8857379 , 0.1142621 ],
       [0.113633  , 0.886367  ],
       [0.82684375, 0.17315625]])

In [ ]:
for i, j in zip(y_predict.tolist()[51:101],y_predict_proba.tolist()[51:101]):
    print(i,": ",j)

0 :  [0.6060478512789693, 0.3939521487210307]
0 :  [0.7828903318926888, 0.2171096681073113]
0 :  [0.8819429096764859, 0.11805709032351405]
0 :  [0.9631220629967343, 0.036877937003265734]
0 :  [0.9093808272361089, 0.09061917276389106]
0 :  [0.6606009851895366, 0.3393990148104634]
0 :  [0.8769271230494882, 0.12307287695051183]
0 :  [0.9556657634586793, 0.04433423654132078]
0 :  [0.9675324373152573, 0.03246756268474268]
0 :  [0.8966981197055346, 0.10330188029446535]
0 :  [0.8893420424829119, 0.11065795751708804]
0 :  [0.8012337980467988, 0.19876620195320116]
0 :  [0.9566360563638094, 0.04336394363619051]
0 :  [0.837462339357592, 0.162537660642408]
0 :  [0.9665733535488247, 0.03342664645117535]
0 :  [0.7583331768444482, 0.2416668231555518]
0 :  [0.8581780704863943, 0.1418219295136057]
0 :  [0.8489050437166132, 0.15109495628338682]
0 :  [0.8732566042832366, 0.1267433957167634]
0 :  [0.8876243867845722, 0.1123756132154278]
0 :  [0.9563669122443794, 0.04363308775562063]
0 :  [0.9088337958741631, 0.09116620412583688]
0 :  [0.7858702810835477, 0.2141297189164523]
0 :  [0.9351716810419612, 0.06482831895803876]
0 :  [0.8149637124586444, 0.1850362875413556]
0 :  [0.7777691637384844, 0.22223083626151566]
0 :  [0.9163790263643818, 0.08362097363561814]
0 :  [0.8574353484181666, 0.14256465158183337]
0 :  [0.6035557728951313, 0.3964442271048687]
1 :  [0.42651178818087, 0.57348821181913]
0 :  [0.9387203089457565, 0.06127969105424344]
0 :  [0.92998450899254, 0.0700154910074599]
0 :  [0.8984488118156778, 0.10155118818432216]
0 :  [0.9640317147308362, 0.03596828526916385]
0 :  [0.7396316223085697, 0.2603683776914303]
0 :  [0.8345938678388153, 0.1654061321611847]
0 :  [0.873347767301417, 0.12665223269858297]
0 :  [0.9326286035333857, 0.0673713964666143]
0 :  [0.9507722995107067, 0.049227700489293306]
0 :  [0.8867314282322268, 0.1132685717677732]
0 :  [0.8021315545542038, 0.19786844544579618]
0 :  [0.7356044483643754, 0.26439555163562456]
0 :  [0.9006536463220026, 0.09934635367799735]
0 :  [0.9486197815038718, 0.05138021849612815]
0 :  [0.9360674400904205, 0.06393255990957941]
0 :  [0.931278002894454, 0.06872199710554609]
0 :  [0.867090530618696, 0.13290946938130394]
0 :  [0.8986956376686841, 0.10130436233131587]
0 :  [0.8619765132597734, 0.13802348674022655]
0 :  [0.7106423195925067, 0.28935768040749327]

In [ ]:
Log_model.coef_

array([[ 0.21081818,  0.5739097 ,  0.03996082, -0.01987565,  0.28910686,
         0.04188776,  0.07348803,  0.09013513,  0.00235399,  0.03927328,
         0.30802619,  0.02145442, -0.01954428, -0.06454334,  0.18605373]])

In [ ]:
Log_model.intercept_

array([-1.9713964])

In [ ]:
accuracy_score(y_test,y_predict)

0.8573113207547169

In [ ]:
df['TenYearCHD'].value_counts()

TenYearCHD
0    3594
1     644
Name: count, dtype: int64

In [ ]:
df['TenYearCHD'].value_counts(normalize=True)*100

TenYearCHD
0    84.804153
1    15.195847
Name: proportion, dtype: float64

In [ ]:
#classification report
from sklearn.metrics import classification_report
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.86      0.99      0.92       724
           1       0.60      0.07      0.13       124

    accuracy                           0.86       848
   macro avg       0.73      0.53      0.53       848
weighted avg       0.82      0.86      0.81       848